// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTsV5oSFuzWhy7T-WKLqFFcMr1yAsJhU4',
    appId: '1:501911573195:web:c57590425415417e26014e',
    messagingSenderId: '501911573195',
    projectId: 'all-in-one-auth-7c3c9',
    authDomain: 'all-in-one-auth-7c3c9.firebaseapp.com',
    storageBucket: 'all-in-one-auth-7c3c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbWzXRHt7Krwsr2HM11Ij3v_rxSCo-nkg',
    appId: '1:501911573195:android:3716eae104a039e826014e',
    messagingSenderId: '501911573195',
    projectId: 'all-in-one-auth-7c3c9',
    storageBucket: 'all-in-one-auth-7c3c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTgyVRn-hF3oezsbUm6bDWbNMoe6_TSIk',
    appId: '1:501911573195:ios:e333d8fb3d5fc7fc26014e',
    messagingSenderId: '501911573195',
    projectId: 'all-in-one-auth-7c3c9',
    storageBucket: 'all-in-one-auth-7c3c9.appspot.com',
    iosBundleId: 'com.example.allInOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTgyVRn-hF3oezsbUm6bDWbNMoe6_TSIk',
    appId: '1:501911573195:ios:04249484e5ca0dd026014e',
    messagingSenderId: '501911573195',
    projectId: 'all-in-one-auth-7c3c9',
    storageBucket: 'all-in-one-auth-7c3c9.appspot.com',
    iosBundleId: 'com.example.allInOne.RunnerTests',
  );
}
